# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from masonite.environment import LoadEnvironment, env
from masoniteorm.connections import ConnectionResolver

DATABASES = {'default': env('DB_CONNECTION', 'sqlite'), 'testing': {'driver': 'sqlite', 'database': env('SQLITE_DB_DATABASE', 'masonite.sqlite3'), 'prefix': '', 'log_queries': env('DB_LOG')}, 'bitacora': {'driver': 'sqlite', 'database': 'bitacora.db', 'prefix': '', 'log_queries': env('DB_LOG')}, 'sqlite': {'driver': 'sqlite', 'database': env('SQLITE_DB_DATABASE', 'masonite.sqlite3'), 'prefix': '', 'log_queries': env('DB_LOG')}, 'mysql': {'driver': 'mysql', 'host': env('DB_HOST'), 'user': env('DB_USERNAME'), 'password': env('DB_PASSWORD'), 'database': env('DB_DATABASE'), 'port': env('DB_PORT'), 'prefix': '', 'grammar': 'mysql', 'options': {'charset': 'utf8mb4'}, 'log_queries': env('DB_LOG')}, 'postgres': {'driver': 'postgres', 'host': env('DB_HOST'), 'user': env('DB_USERNAME'), 'password': env('DB_PASSWORD'), 'database': env('DB_DATABASE'), 'port': env('DB_PORT'), 'prefix': '', 'grammar': 'postgres', 'log_queries': env('DB_LOG')}, 'mssql': {'driver': 'mssql', 'host': env('MSSQL_DATABASE_HOST'), 'user': env('MSSQL_DATABASE_USER'), 'password': env('MSSQL_DATABASE_PASSWORD'), 'database': env('MSSQL_DATABASE_DATABASE'), 'port': env('MSSQL_DATABASE_PORT'), 'prefix': '', 'log_queries': env('DB_LOG')}}

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import masonite
import masonite.environment
import masonite.environment.LoadEnvironment
import masonite.environment.env
import masoniteorm
import masoniteorm.connections
import masoniteorm.connections.ConnectionResolver